version: '3.3'
services:
  db: 
    image: mysql:5.7 
    restart: always
    environment:
      - MYSQL_DATABASE=CCI
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - type: volume
        source: db-volumes
        target: /var/lib/mysql

  app:
    image: jeronimojr/cci-docker
    ports:
      - 3000:3000
    expose:
      - 3000
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - NODE_ENV=production
    depends_on:
      - db
    links:
      - db

networks:
  default:
    driver: bridge
  
volumes:
  db-volumes: